export const EXERC_GET_DATA = 'EXERC_GET_DATA'
export const EXERC_GET_DATA_FAIL = 'EXERC_GET_DATA_FAIL'
export const EXERC_EDIT = 'EXERC_EDIT'
export const EXERC_ADD = 'EXERC_ADD'
export const EXERC_DELETE = 'EXERC_DELETE'
export const EXERC_CLEAR_SESSION = 'EXERC_CLEAR_SESSION'






